### ISSUE TITLE
OK to add some docs?

### ISSUE THREAD

**Issue by smeyfroi** [dimitre/ofxMicroUI#1]
Have started to integrate this UI into my current project: impressed with functionality!

I'd like to raise a PR to add to the readme if that would be useful?

I find I'm having to find answers from the source, so I think docs could be improved a little. Is that worth me having a go at?

**Comment by dimitre** [comment]
Oh thank you! yes any PR will be welcome. I have outdated examples but I'll be happy to provide more things soon

**Comment by smeyfroi** [comment]
Closing. Will raise a PR.
